[tasks.install-dev]
script = '''
brew install fuyutarow/tap/pq
'''


[tasks.concat-ja]
script = '''
mkdir -p tmp
for i in $(seq 1 8); do
    pq ja/gen$i-jp.json -t yaml > tmp/$i.yml
done
cat tmp/* | pq -f yaml -t json -c > ja/pokemon.json
rm -rf tmp
'''
